export const ADD_SELECTED_INGREDIENT = 'ADD_SELECTED_INGREDIENT';
export const REMOVE_SELECTED_INGREDIENT = 'REMOVE_SELECTED_INGREDIENT';
export const CHANGE_SELECTED_INGREDIENTS_ORDER = 'CHANGE_SELECTED_INGREDIENTS_ORDER';
